import { useEffect, useState } from "react";
import { api } from "../api";
import { useAuth } from "../AuthContext";

export default function AdminDashboard() {
  const { session } = useAuth(); const [overview, setOverview] = useState({}); const [accounts, setAccounts] = useState([]); const [form, setForm] = useState({ elder_user_id: "", caregiver_id: "" }); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { try { const [o, a] = await Promise.all([api.adminOverview(session.token), api.adminAccounts(session.token)]); setOverview(o); setAccounts(a || []); } catch (err) { setError(err.message); } }
  useEffect(() => { load(); }, []);
  async function assign(e) { e.preventDefault(); setError(""); try { await api.adminAssign(session.token, form); setMessage("Caregiver assigned successfully."); setForm({ elder_user_id: "", caregiver_id: "" }); load(); } catch (err) { setError(err.message); } }
  return <div className="container"><div className="card"><h2>System overview</h2><div className="stats-grid">{[["Elders", overview.elder], ["Caregivers", overview.caregiver], ["Family viewers", overview.family], ["Active assignments", overview.assignments], ["Open alerts", overview.open_alerts]].map(([label, value]) => <div className="stat" key={label}><strong>{value ?? "–"}</strong><span>{label}</span></div>)}</div></div><div className="management-grid"><div className="card"><h2>Assign caregiver to elder</h2><form className="stack" onSubmit={assign}><div><label>Elder user ID</label><input type="number" min="1" required value={form.elder_user_id} onChange={e => setForm({...form, elder_user_id: Number(e.target.value)})}/></div><div><label>Caregiver ID</label><input type="number" min="1" required value={form.caregiver_id} onChange={e => setForm({...form, caregiver_id: Number(e.target.value)})}/></div><button>Save assignment</button></form></div><div className="card"><h2>Accounts</h2><p className="muted">Latest 200 accounts; use this as the system oversight view.</p><div className="table-scroll"><table><thead><tr><th>ID</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{accounts.map(a => <tr key={a.account_id}><td>{a.account_id}</td><td>{a.email}</td><td>{a.Role}</td><td>{a.active ? "Active" : "Inactive"}</td></tr>)}</tbody></table></div></div></div>{error && <div className="error">{error}</div>}{message && <div className="success">{message}</div>}</div>;
}
